/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jansen_com_smartupdate_UpdateUtil */

#ifndef _Included_jansen_com_smartupdate_UpdateUtil
#define _Included_jansen_com_smartupdate_UpdateUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jansen_com_smartupdate_UpdateUtil
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jansen_com_smartupdate_UpdateUtil_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
